instrument boot process with simple webpage

diff --git a/net/serval-mesh-extender/files/etc/rc.d/S47mountstuff b/net/serval-mesh-extender/files/etc/rc.d/S47mountstuff
--- a/net/serval-mesh-extender/files/etc/rc.d/S47mountstuff
+++ b/net/serval-mesh-extender/files/etc/rc.d/S47mountstuff
@@ -5,11 +5,17 @@ START=47
 
 start() {
 
+    # Start httpd for tracking boot progress
+    mkdir /tmp/www
+    httpd -h /tmp/www
+    /etc/serval/boot_report OK "Entering S47mountstuff"    
+    
   if [ -e /dev/mmcblk0 ]; then
      # Bulk storage on SPI microSD
      dev=/dev/mmcblk0p
      if [ ! -e /dev/mmcblk0p3 ]; then
-       # microSD card is not partitioned, so prepare it
+	 # microSD card is not partitioned, so prepare it
+	     /etc/serval/boot_report WARN "microSD card not partitioned -- running fdisk"    
        fdisk /dev/mmcblk0 <<EOF
 d
 1
@@ -45,76 +51,93 @@ EOF
 
      fi
   else
-     if [  -e /dev/sda1 ]; then
-        # Bulk storage on USB
+      /etc/serval/boot_report WARN "No microSD card present"    
+
+      if [  -e /dev/sda1 ]; then
+          # Bulk storage on USB
+	  /etc/serval/boot_report OK "Found USB bulk storage"    
+
         dev=/dev/sda
      else
         # XXX - No bulk storage -- work out what to do.
         # We are now using microSD instead of USB, so our remedial options are different
+	 /etc/serval/boot_report WARN "No USB or microSD card.  This is not recommended, and may rapidly wear out the flash storage of your Mesh Extender"
         exit
      fi
   fi
 
+  /etc/serval/boot_report OK "Making sure bulk storage unmounted"
   umount /dos
   umount /serval
   umount /serval-var
 
+  /etc/serval/boot_report OK "Checking integrity of /serval"
   fsck.ext2 -y ${dev}2
+  /etc/serval/boot_report OK "Checking integrity of /serval-var"
   fsck.ext2 -y ${dev}3
+  /etc/serval/boot_report OK "Checking integrity of /dos"
   dosfsck -y ${dev}1
   
   umount /dos
   mount ${dev}1 /dos
   if [ $? == 255 ]; then    
+    /etc/serval/boot_report ERROR "Failed to mount /dos on first attempt -- reformatting"
     echo "Reformatting /dos"
     mkfs.vfat ${dev}1
     mount ${dev}1 /dos
+    if [ $? == 0 ]; then
+	/etc/serval/boot_report OK "Mounted /dos"
+    else
+	/etc/serval/boot_report ERROR "Could not mount /dos"
+    fi
+  else
+    /etc/serval/boot_report OK "Mounted /dos"
   fi
   mount ${dev}2 /serval > /tmp/mount2.error 2>&1
   if [ $? == 255 ]; then
+     /etc/serval/boot_report ERROR "Failed to mount /serval on first attempt"
      reformat=`cat /tmp/mount2.error | egrep "Invalid argument|Super|super" | wc -l`
      if [ "x$reformat" != "x0" ]; then
+       /etc/serval/boot_report WARN "Reformatting /serval"
        echo "Reformatting /serval"
        mkfs.ext2 ${dev}2
        mount ${dev}2 /serval
+       if [ $? == 0 ]; then
+	   /etc/serval/boot_report OK "Mounted /serval"
+       else
+	   /etc/serval/boot_report ERROR "Could not mount /serval"
+       fi
      fi
+  else
+    /etc/serval/boot_report OK "Mounted /serval"
   fi
   mount ${dev}3 /serval-var > /tmp/mount3.error 2>&1
   if [ $? == 255 ]; then
+     /etc/serval/boot_report ERROR "Failed to mount /serval-var on first attempt"
      reformat=`cat /tmp/mount3.error | egrep "Invalid argument|Super|super" | wc -l`
      if [ "x$reformat" != "x0" ]; then
+       /etc/serval/boot_report WARN "Reformatting /serval-var"
        echo "Reformatting /serval-var"
        mkfs.vfat ${dev}3
        mount ${dev}3 /serval-var
-    fi
+       if [ $? == 0 ]; then
+	   /etc/serval/boot_report OK "Mounted /serval-var"
+       else
+	   /etc/serval/boot_report ERROR "Could not mount /serval-var"
+       fi
+     fi
   fi
 
   mount > /tmp/mount47.log
-
   dosmounted=`mount | grep /dos | wc -l`
 
-  if [ -e ${dev}1 ] && [ "x$dosmounted" == "x0" ]; then
-    # on first boot, the partitions are mounted under /tmp instead of in
-    # the right place, so reboot
-    sleep 60 # Give us time to log in remotely to fix anything broken
-    reboot
-  fi
-  # If that wasn't the problem, and there is no device, or it hasn't mounted,
-  # then we have a bigger problem ...
-  if [ ! -e ${dev}1 ] || [ -e /serval/MeshExtender ] || [ -e /serval-var/MeshExtender ]; then
-    # No storage present, or failed to mount -- this can be caused by a known hardware bug
-    # in the Atheros 9k USB host controller. It can only be fixed by 
-    # physically removing power -- a soft reset doesn't work.
-    # To at least alert the user that this is happening, we will
-    # blink the LEDs in a distinctive pattern.
-    # XXX - We might be able to use the GPIO that cuts USB host power to fix this situation.
-    echo "WARNING: Could not mount /serval or /serval-var"  
-  fi 
+  /etc/serval/boot_report OK "Finished mounting file systems"
 
   # Finally, read the EEPROM on the power cable, and set some parameters
   # The radio is in silent mode on power up, so we need to make sure we allow
   # enough time for it to exit silent mode, or else we need to tell the radio to
   # exit silent mode when asked to dump eeprom contents.
+  /etc/serval/boot_report OK "Reading Radio EEPROM settings"
   flash900 eeprom /dev/ttyATH0 directives list > /serval-var/eeprom.directives
   otabid=`flash900 eeprom /dev/ttyATH0 directives get OTABID | cut -f2 -d=`
   yesroot=`flash900 eeprom /dev/ttyATH0 directives get YESROOT | cut -f2 -d=`
@@ -130,7 +153,11 @@ EOF
     touch /dos/noroot
     rm /dos/yesroot
   fi
+  lines=`wc -l < /serval-var/eeprom.directives`
+  /etc/serval/boot_report OK "Read Radio EEPROM settings (${lines} lines)"
+
+  /etc/serval/boot_report OK "Exiting S47mountstuff"    
+
   
- 
 }
 
