add S50dropbear to new www bootlog framework

diff --git a/net/serval-mesh-extender/files/etc/init.d/dropbear b/net/serval-mesh-extender/files/etc/init.d/dropbear
--- a/net/serval-mesh-extender/files/etc/init.d/dropbear
+++ b/net/serval-mesh-extender/files/etc/init.d/dropbear
@@ -15,97 +15,103 @@ EXTRA_HELP="	killclients Kill ${NAME} processes except servers and yourself"
 
 dropbear_start()
 {
-	# Only run dropbear if there does not exist a file /dos/noroot
-	# If starting, create the file, so that removing noroot only allows
-	# ssh to be available for one boot.
-	passwd -l root # lock root
-        # /dos/yesroot causes root access to always be available
-        if [ ! -e /dos/yesroot ]; then
-          [ -e /dos/noroot ] && return 1
-          touch /dos/noroot
-          echo "Remove this file to enable SSH login to the mesh extender as root:root." >/dos/noroot
-          echo "This file is recreated on each reboot, so is effective for one boot only." >>/dos/noroot
-        fi
-        passwd -u root # unlock root if allowing dropbear
-        ( sleep 1; echo "root" ; sleep 1; echo "root" ) | passwd root
-        if [ -e /dos/yesroot ]; then
-          if [ ! -z /dos/yesroot ]; then
+    /etc/serval/boot_report OK "Entering S50dropbear"
+    
+    # Only run dropbear if there does not exist a file /dos/noroot
+    # If starting, create the file, so that removing noroot only allows
+    # ssh to be available for one boot.
+
+    /etc/serval/boot_report OK "Locking root password"
+    passwd -l root # lock root
+    # /dos/yesroot causes root access to always be available
+    if [ ! -e /dos/yesroot ]; then
+        [ -e /dos/noroot ] && return 1
+        touch /dos/noroot
+        echo "Remove this file to enable SSH login to the mesh extender as root:root." >/dos/noroot
+        echo "This file is recreated on each reboot, so is effective for one boot only." >>/dos/noroot
+    fi
+    /etc/serval/boot_report OK "Enabling SSH login"
+    passwd -u root # unlock root if allowing dropbear
+    ( sleep 1; echo "root" ; sleep 1; echo "root" ) | passwd root
+    if [ -e /dos/yesroot ]; then
+        if [ ! -z /dos/yesroot ]; then
             # Set root password according to contents of yesroot file
+	    /etc/serval/boot_report OK "Setting root password"
             password=`cat /dos/yesroot | cut -c1-8`
             ( sleep 1; echo "${password}" ; sleep 1; echo "${password}" ) | passwd root
-          fi 
-        fi
-
-	append_ports()
-	{
-		local ifname="$1"
-		local port="$2"
-
-		grep -qs "^ *$ifname:" /proc/net/dev || {
-			append args "-p $port"
-			return
-		}
-
-		for addr in $(
-			ifconfig "$ifname" | sed -ne '
-				/addr: *fe[89ab][0-9a-f]:/d
-				s/.* addr: *\([0-9a-f:\.]*\).*/\1/p
-			'
-		); do
-			append args "-p $addr:$port"
-		done
+        fi 
+    fi
+    
+    append_ports()
+    {
+	local ifname="$1"
+	local port="$2"
+	
+	grep -qs "^ *$ifname:" /proc/net/dev || {
+	    append args "-p $port"
+	    return
 	}
-
-
-	local section="$1"
-
-	# check if section is enabled (default)
-	local enabled
-	config_get_bool enabled "${section}" enable 1
-	[ "${enabled}" -eq 0 ] && return 1
-
-	# verbose parameter
-	local verbosed
-	config_get_bool verbosed "${section}" verbose 0
-
-	# increase pid file count to handle multiple instances correctly
-	PIDCOUNT="$(( ${PIDCOUNT} + 1))"
-
-	# prepare parameters (initialise with pid file)
-	local pid_file="/var/run/${NAME}.${PIDCOUNT}.pid"
-	local args="-P $pid_file"
-	local val
-	# A) password authentication
-	config_get_bool val "${section}" PasswordAuth 1
-	[ "${val}" -eq 0 ] && append args "-s"
-	# B) listen interface and port
-	local port
-	local interface
-	config_get interface "${section}" Interface
-	config_get interface "${interface}" ifname "$interface"
-	config_get port "${section}" Port 22
-	append_ports "$interface" "$port"
-	# C) banner file
-	config_get val "${section}" BannerFile
-	[ -f "${val}" ] && append args "-b ${val}"
-	# D) gatewayports
-	config_get_bool val "${section}" GatewayPorts 0
-	[ "${val}" -eq 1 ] && append args "-a"
-	# E) root password authentication
-	config_get_bool val "${section}" RootPasswordAuth 1
-	[ "${val}" -eq 0 ] && append args "-g"
-	# F) root login
-	config_get_bool val "${section}" RootLogin 1
-	[ "${val}" -eq 0 ] && append args "-w"
-	# G) host keys
-	config_get val "${section}" rsakeyfile
-	[ -f "${val}" ] && append args "-r ${val}"
-	config_get val "${section}" dsskeyfile
-	[ -f "${val}" ] && append args "-d ${val}"
-
-	# execute program and return its exit code
-	[ "${verbosed}" -ne 0 ] && echo "${initscript}: section ${section} starting ${PROG} ${args}"
-	SERVICE_PID_FILE="$pid_file" service_start ${PROG} ${args}
+	
+	for addr in $(
+			 ifconfig "$ifname" | sed -ne '
+			 	/addr: *fe[89ab][0-9a-f]:/d
+					s/.* addr: *\([0-9a-f:\.]*\).*/\1/p
+			'		
+		     ); do
+	    append args "-p $addr:$port"
+	done
+    }
+    
+    
+    local section="$1"
+    
+    # check if section is enabled (default)
+    local enabled
+    config_get_bool enabled "${section}" enable 1
+    [ "${enabled}" -eq 0 ] && return 1
+    
+    # verbose parameter
+    local verbosed
+    config_get_bool verbosed "${section}" verbose 0
+    
+    # increase pid file count to handle multiple instances correctly
+    PIDCOUNT="$(( ${PIDCOUNT} + 1))"
+    
+    # prepare parameters (initialise with pid file)
+    local pid_file="/var/run/${NAME}.${PIDCOUNT}.pid"
+    local args="-P $pid_file"
+    local val
+    # A) password authentication
+    config_get_bool val "${section}" PasswordAuth 1
+    [ "${val}" -eq 0 ] && append args "-s"
+    # B) listen interface and port
+    local port
+    local interface
+    config_get interface "${section}" Interface
+    config_get interface "${interface}" ifname "$interface"
+    config_get port "${section}" Port 22
+    append_ports "$interface" "$port"
+    # C) banner file
+    config_get val "${section}" BannerFile
+    [ -f "${val}" ] && append args "-b ${val}"
+    # D) gatewayports
+    config_get_bool val "${section}" GatewayPorts 0
+    [ "${val}" -eq 1 ] && append args "-a"
+    # E) root password authentication
+    config_get_bool val "${section}" RootPasswordAuth 1
+    [ "${val}" -eq 0 ] && append args "-g"
+    # F) root login
+    config_get_bool val "${section}" RootLogin 1
+    [ "${val}" -eq 0 ] && append args "-w"
+    # G) host keys
+    config_get val "${section}" rsakeyfile
+    [ -f "${val}" ] && append args "-r ${val}"
+    config_get val "${section}" dsskeyfile
+    [ -f "${val}" ] && append args "-d ${val}"
+    
+    # execute program and return its exit code
+    [ "${verbosed}" -ne 0 ] && echo "${initscript}: section ${section} starting ${PROG} ${args}"
+    SERVICE_PID_FILE="$pid_file" service_start ${PROG} ${args}
 }
 
 keygen()
@@ -209,4 +215,7 @@ killclients()
 		echo "${initscript}: Killing ${pid}..."
 		kill -KILL ${pid}
 	done
+
+    /etc/serval/boot_report OK "Exiting S50dropbear"
+	
 }
